name: Build
on:
  - push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v4

      - name: Cache the virtualenv
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install Poetry dependencies
        run: poetry install

      - name: Run black
        run: poetry run black --check gatech_slack_account_fixer.py

      - name: Run flake8
        run: poetry run flake8 gatech_slack_account_fixer.py

      - name: Run pylint
        run: poetry run pylint gatech_slack_account_fixer.py

      - name: Run mypy
        run: poetry run mypy --strict --scripts-are-modules gatech_slack_account_fixer.py
